package com.bookflow.common.enums;

public enum AuditAction {
	BUSINESS_CREATED,
	BUSINESS_UPDATED,
	BUSINESS_DELETED,
	SERVICE_CREATED,
	SERVICE_UPDATED,
	SERVICE_DELETED,
	STAFF_CREATED,
	STAFF_UPDATED,
	STAFF_DELETED,
	AVAILABILITY_CREATED,
	AVAILABILITY_UPDATED,
	AVAILABILITY_DELETED,
	TIME_OFF_CREATED,
	TIME_OFF_DELETED,
	BOOKING_CREATED,
	BOOKING_CONFIRMED,
	BOOKING_CANCELLED,
	BOOKING_COMPLETED,
	BOOKING_NO_SHOW
}
