package com.bookflow.common.exception;

public enum ErrorCode {
	VALIDATION_ERROR,
	UNAUTHORIZED,
	FORBIDDEN,
	RESOURCE_NOT_FOUND,
	DUPLICATE_RESOURCE,
	BAD_REQUEST,
	CONFLICT,
	BUSINESS_RULE_VIOLATION,
	BOOKING_SLOT_UNAVAILABLE,
	OPTIMISTIC_LOCK_CONFLICT,
	INTERNAL_SERVER_ERROR
}
